### PR TITLE
llvm 3.8.1

### PR DESCRIPTION
**Pull request by killerswan**

### CODE REVIEW

**Comment by killerswan** [comment]
I hope this build doesn't time out! 🙀

**Comment by killerswan** [comment]
Welp (e.g., [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/215471308/log.txt)):
```
The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Comment by killerswan** [comment]
1. I'll try again late tonight when traffic is lower.
1. We need to put root URLs for the other formulas' bottles in!! 🙀 
1. If we have to do local builds of LLVM we can do that and stick them on GitHub or something and then use a different root URL for LLVM, skipping the Travis builds.   NOT sure I like this, but it's possible...

Srsly, I don't wanna sign up for maintaining my own Travis / Jenkins instance just to build LLVMs that we're not sure Homebrew core will keep around. 😝

**Comment by killerswan** [comment]
Some ideas:
* get lucky with late-night stuff (unlikely),
* talk to Travis CI people about extended limits,
* mirror and don't rebuild Homebrew core packages (keep the same SHA, just change root URL),
* get lucky with Circle CI or Concourse CI or whatever has more capacity for open source.

**Comment by killerswan** [comment]
A fifth possibility, since @jemc already has some CI infrastructure set up, would be to add a macOS VM or two somewhere that works with his system: http://ci.ilvain.com/

Although today/tomorrow I'm just going to do simple mirroring from homebrew-core and try to keep it simpler.

**Comment by jemc** [comment]
My personal CI infrastructure isn't in very good shape at the moment.  I don't think we should rely on it being of any use, unfortunately.

**Comment by jemc** [comment]
@killerswan - just wondering - why not use the LLVM binaries that they build & distribute from the llvm.org website?

**Comment by killerswan** [comment]
That's leaving homebrew behind.  You're right, though, it's worth looking at, too.

**Comment by jemc** [comment]
Sorry I don't know much about homebrew.  I just don't know if you're going to have much luck finding a free CI that wants to let you do big LLVM builds.

**Comment by killerswan** [comment]
Well, there's plenty of software out there which takes even longer to build.

But you know if the upstream LLVM macOS builds are _almost_ what we need, it may be easier to convince them to add whatever else we need and help out that project directly.

**Pull request closed without merging**
